apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  project: default
  source:
    path: ./charts/metrics-server/
    repoURL:  https://github.com/jeliasmoreira/gitops.git
    helm:
      releaseName: metrics-server
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
