apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-registry
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  project: default
  source:
    path: ./charts/nxrm/
    repoURL:  https://github.com/jeliasmoreira/gitops.git
    helm:
      releaseName: nexus-registry
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
