apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ngnix
  name: ngnix
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngnix
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngnix
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
