apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx
  namespace: nginx
  labels:
    app: ngnix  
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: ngnix
  type: LoadBalancer
