apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx
    namespace: nginx
  labels:
    app: ngnix  
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: ngnix
  type: LoadBalancer
